version: '3.9'

services:
  app:
    build: ./
    container_name: load-balancer
    command: /app/cmd/main
    ports:
      - "3030:3030"
    environment:
      CONFIG: configs/dev.yaml
  web1:
    image: strm/helloworld-http
  web2:
    image: strm/helloworld-http
  web3:
    image: strm/helloworld-http
  web4:
    image: strm/helloworld-http
  web5:
    image: strm/helloworld-http

